#menggunakan versi 3 dari docker compose
version: '3'

#Membuat 2 services dengan nama item-app dan item-db
services:
  item-app:
    #menggunakan base image dari github packages buatan sendiri
    image: ghcr.io/praset911/item-app:v1
    #menggunakan port 80 untuk host , dan 8080 untuk container
    ports:
      - '80:8080'
    #digunakan agar service ini bisa berjalan jika service item-db sudah diluncurkan
    depends_on:
      - item-db
    #digunakan agar container selalu restart ketika terhenti
    restart: always

  item-db:
    #menggunakan base image "mongo" versi 3 dari docker hub
    image: mongo:3
    #memakai volumes bernama app-db dengan target /data/db
    volumes:
      - app-db:/data/db
    #digunakan agar container selalu restart ketika terhenti
    restart: always

#membuat volumes bernama app-db
volumes:
  app-db:
