version: 2.1
orbs:
  docker: circleci/docker@2.2.0
jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile
  test-app:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run: |
          go test -v -short --count=1 $(go list ./...)
  build-app-karsajobs:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - run: |
          . build_push_image_karsajobs.sh

workflows:
  lint-dockerfile:
    jobs:
      - lint-dockerfile
  test-app:
    jobs:
      - test-app
  build-app-karsajobs:
    jobs:
      - build-app-karsajobs
