apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  labels:
    app: shipping
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: shipping-service
