apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-deployment
  labels:
    app: shipping
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
        - name: shipping-container
          image: ghcr.io/praset911/shipping-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
      env:
        - name: AMQP_URL
          value: 'amqp://my-rabbitmq.default.svc.cluster.local:5672'
